fixed js issue caused by null $visibleEl and $invisibleEl
algoritmika/product-visibility-by-user-role-for-woocommerce pull request #1
Opened 2021-08-25 14:24 UTC by amir-canteetu

2021-08-26 12:45 UTC, grantalltodavid requested changes
your solution looks fine but we should do the same thing on lines 16 and 19 as well.

2021-08-26 12:45 UTC, grantalltodavid commented on includes/js/admin.js
>  			} else if ( $visibleEl.val().length ) {
I just noticed we should make the same change here on line 16, and also line 19 below.

2021-08-26 14:54 UTC, amir-candido commented on includes/js/admin.js
>  			} else if ( $visibleEl.val().length ) {
Done.

2021-08-31 11:50 UTC, grantalltodavid approved these changes

2021-08-31 11:50 UTC, merged